### ISSUE TITLE
[simulator] sqlite3.OperationalError: database is locked`

### ISSUE THREAD

**Issue by DJTOMATO** [hollowstrawberry/crab-cogs#23]
While doing ``simulator feed``

apparently the process still finishes and works, but saw this error, just in case
``` [2023-06-26 22:18:43] [ERROR] discord.client: Ignoring exception in on_message
 Traceback (most recent call last):
   File "/home/glas/redenv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
     await coro(*args, **kwargs)
   File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/simulator/simulator.py", line 377, in on_message
     await self.insert_message_db(message, db)
   File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/simulator/simulator.py", line 586, in insert_message_db
     await db.execute(f'INSERT INTO {DB_TABLE_MESSAGES} VALUES (?, ?, ?)',
   File "/home/glas/redenv/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
     cursor = await self._execute(self._conn.execute, sql, parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/glas/redenv/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
     return await future
            ^^^^^^^^^^^^
   File "/home/glas/redenv/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
     result = function()
              ^^^^^^^^^^
 sqlite3.OperationalError: database is locked
```

**Comment by hollowstrawberry** [comment]
Ah, I think this is expected, but I'll keep it in mind. Thanks.
