### ISSUE TITLE
EasyTranslate won't Load

### ISSUE THREAD

**Issue by DorwardTech** [hollowstrawberry/crab-cogs#25]
Red version 3.5.2

[2023-07-23 03:08:04] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/home/container/.local/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension
    lib = spec.loader.load_module()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager/cogs/easytranslate/__init__.py", line 1, in <module>
    from .easytranslate import EasyTranslate
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager/cogs/easytranslate/easytranslate.py", line 25, in <module>
    import googletrans
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/Downloader/lib/googletrans/__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/Downloader/lib/googletrans/client.py", line 12, in <module>
    import httpx
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/Downloader/lib/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/Downloader/lib/httpx/_api.py", line 3, in <module>
    from ._client import Client, StreamContextManager
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/Downloader/lib/httpx/_client.py", line 8, in <module>
    from ._auth import Auth, BasicAuth, FunctionAuth
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/Downloader/lib/httpx/_auth.py", line 9, in <module>
    from ._exceptions import ProtocolError, RequestBodyUnavailable
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/Downloader/lib/httpx/_exceptions.py", line 43, in <module>
    CloseError = httpcore.CloseError
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'httpcore' has no attribute 'CloseError'

assumption will be because of the translate version is pretty old now, anychance of migrating it forward?
https://stackoverflow.com/questions/72796594/attributeerror-module-httpcore-has-no-attribute-synchttptransport

**Comment by DorwardTech** [comment]
not your problem :) was a buster issue
